version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: video_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - video_encoding
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s

  fastapi:
    build:
      context: .
      dockerfile: ./compose/fastapi/Dockerfile
    container_name: video_fastapi
    depends_on:
      mysql:
        condition: service_healthy
      dragonfly:
        condition: service_started
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DRAGONFLY_URL: ${DRAGONFLY_URL}
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi/app:/app
    networks:
      - video_encoding
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    container_name: video_dragonfly
    restart: always
    ports:
      - "6379:6379"  # Default Redis-compatible port
    networks:
      - video_encoding
    command: ["dragonfly", "--port", "6379"]


volumes:
  mysql_data:

networks:
  video_encoding:
    driver: bridge

